INSERT INTO [dbo].[SpellListSpell] (SpellListId, SpellId)
	VALUES 
		   --Cantrips--
		   (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Acid Splash')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Blade Ward')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Chill Touch')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Dancing Lights')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fire Bolt')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Friends')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Light')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mage Hand')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mending')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Message')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Minor Illusion')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Poison Spray')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Shocking Grasp')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'True Strike')),

		   --Level 1--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Alarm')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Burning Hands')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Charm Person')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Chromatic Orb')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Color Spray')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Comprehend Languages')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Detect Magic')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Disguise Self')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Expeditious Retreat')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'False Life')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Feather Fall')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Find Familiar')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fog Cloud')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Grease')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Identify')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Illusory Script')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Jump')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Longstrider')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mage Armor')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Magic Missile')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Protection from Evil and Good')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Ray of Sickness')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Shield')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Silent Image')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Sleep')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Tasha''s Hideous Laughter')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Tenser''s Floating Disk')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Thunderwave')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Unseen Servant')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Witch Bolt')),

		   --Level 2--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Alter Self')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Arcane Lock')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Blindness/Deafness')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Blur')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Cloud of Daggers')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Continual Flame')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Crown of Madness')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Darkness')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Darkvision')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Detect Thoughts')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Enlarge/Reduce')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Flaming Sphere')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Gentle Repose')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Gust of Wind')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Hold Person')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Invisibility')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Knock')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Levitate')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Locate Object')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Magic Mouth')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Magic Weapon')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Melf''s Acid Arrow')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mirror Image')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Misty Step')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Nystul''s Magic Aura')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Phantasmal Force')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Ray of Enfeeblement')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Rope Trick')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Scorching Ray')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'See Invisibility')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Shatter')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Spider Climb')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Suggestion')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Web')),

		   --Level 3--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Animate Dead')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Bestow Curse')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Blink')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Clairvoyance')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Counterspell')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Dispel Magic')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fear')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Feign Death')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fireball')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fly')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Gaseous Form')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Glyph of Warding')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Haste')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Hypnotic Pattern')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Leomund''s Tiny Hut')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Lightning Bolt')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Magic Circle')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Major Image')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Nondetection')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Phantom Steed')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Protection from Energy')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Remove Curse')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Sending')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Sleet Storm')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Slow')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Stinking Cloud')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Tongues')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Vampiric Touch')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Water Breathing')),

		   --Level 4--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Arcane Eye')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Banishment')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Blight')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Confusion')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Conjure Minor Elementals')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Control Water')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Dimension Door')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Evard''s Black Tentacles')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fabricate')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Fire Shield')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Greater Invisibility')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Hallucinatory Terrain')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Ice Storm')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Leomund''s Secret Chest')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Locate Creature')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mordenkainen''s Faithful Hound')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mordenkainen''s Private Sanctum')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Otiluke''s Resilient Sphere')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Phantasmal Killer')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Polymorph')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Stone Shape')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Stoneskin')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Wall of Fire')),

		   --Level 5--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Animate Objects')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Bigby''s Hand')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Cloudkill')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Cone of Cold')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Conjure Elemental')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Contact Other Plane')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Creation')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Dominate Person')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Dream')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Geas')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Hold Monster')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Legend Lore')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mislead')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Modify Memory')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Passwall')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Planar Binding')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Rary''s Telepathic Bond')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Scrying')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Seeming')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Telekinesis')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Teleportation Circle')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Wall of Force')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Wall of Stone')),

		   --Level 6--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Arcane Gate')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Chain Lightning')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Circle of Death')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Contingency')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Create Undead')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Disintegrate')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Drawmij''s Instant Summons')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Eyebite')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Flesh to Stone')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Globe of Invulnerability')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Guards and Wards')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Magic Jar')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mass Suggestion')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Move Earth')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Otiluke''s Freezing Sphere')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Otto''s Irresistible Dance')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Programmed Illusion')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Sunbeam')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'True Seeing')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Wall of Ice')),


		   --Level 7--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Delayed Blast Fireball')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Etherealness')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Finger of Death')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Forcecage')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mirage Arcane')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mordenkainen''s Magnificent Mansion')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mordenkainen''s Sword')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Plane Shift')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Prismatic Spray')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Project Image')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Reverse Gravity')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Sequester')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Simulacrum')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Symbol')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Teleport')),


		   --Level 8--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Antimagic Field')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Antipathy/Sympathy')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Clone')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Control Weather')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Demiplane')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Dominate Monster')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Feeblemind')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Incendiary Cloud')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Maze')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Mind Blank')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Power Word Stun')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Sunburst')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Telepathy')),


		   --Level 9--
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Astral Projection')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Foresight')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Gate')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Imprisonment')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Meteor Swarm')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Power Word Kill')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Prismatic Wall')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Shapechange')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Time Stop')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'True Polymorph')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Weird')),
	       (8, (SELECT TOP(1) [Id] FROM [dbo].[Spell] WHERE [Name] = 'Wish'))

GO