INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 1, 1, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 2, 1, 2)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 3, 2, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 4, 2, 3)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 5, 3, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 6, 3, 7)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 7, 4, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 8, 5, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 9, 5, 11)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 10, 6, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 11, 6, 5)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 12, 7, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 13, 7, 3)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 14, 8, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 15, 8, 8)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 16, 9, 1)
INSERT INTO [dbo].[RaceLanguage] ([Id],[RaceId], [LanguageId]) VALUES ( 17, 9, 13)
GO