INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 1, 'Common', 'Humans', 'Common', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 2, 'Dwarvish', 'Dwarves', 'Dwarvish', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 3, 'Elvish', 'Elves', 'Elvish', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 4, 'Giant', 'Ogres, Giants', 'Dwarvish', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 5, 'Gnomish', 'Gnomes', 'Dwarvish', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 6, 'Goblin', 'Goblinoids', 'Dwarvish', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 7, 'Halfling', 'Halflings', 'Common', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 8, 'Orc', 'Orcs', 'Dwarvish', 0)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 9, 'Abyssal', 'Demons', 'Infernal', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 10, 'Celestial', 'Celestials', 'Celestial', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 11, 'Draconic', 'Dragons, Dragonborn', 'Draconic', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 12, 'Deep Speech', 'Mind Flayers, Beholders', '-', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 13, 'Infernal', 'Devils', 'Infernal', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 14, 'Primordial', 'Elementals', 'Dwarvish', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 15, 'Sylvan', 'Fey Creatures', 'Elvish', 1)
INSERT INTO [dbo].[Language] ([Id],[Name],[TypicalSpeakers],[Script],[IsExotic]) VALUES ( 16, 'Undercommon', 'Underdark traders', 'Elvish', 1)
GO