INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (1, 'Barbarian', '', 12, 'Primal Path', '', 3, 2, 5, 'barbarian.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (2, 'Bard', '', 8, 'Bard College', '', 3, 3, 6, 'bard.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (3, 'Cleric', '', 8, 'Divine Domain', '', 1, 2, 5, 'cleric.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (4, 'Druid', '', 8, 'Druid Circle', '', 2, 2, 5, 'druid.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (5, 'Fighter', '', 10, 'Martial Archetype', '', 3, 2, 4, 'fighter.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (6, 'Monk', '', 8, 'Monsatic Traditions', '', 3, 2, 5, 'monk.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (7, 'Paladin', 'Whatever their origin and their mission, paladins are united by their oaths to stand against the forces of evil. Whether sworn before a god''s altar and the witness of a priest, in a sacred glade before nature spirits and fey beings, or in a moment of desperation and grief with the dead as the only witness, a paladin''s oath is a powerful bond. It is a source of power that turns a devout warrior into a blessed champion.
<br/>
<br/><strong>THE CAUSE OF RIGHTEOUSNESS</strong>
<br/>A paladin swears to uphold justice and righteousness, to stand with the good things of the world against the encroaching darkness, and to hunt the forces of evil wherever they lurk. Different paladins focus on various aspects of the cause of righteousness, but all are bound by the oaths that grant them power to do their sacred work. Although many paladins are devoted to gods of good, a paladin''s power comes as much from a commitment to justice itself as it does from a god.
<br/>Paladins train for years to learn the skills of combat, mastering a variety of weapons and armor. Even so, their martial skills are secondary to the magical power they wield: power to heal the sick and injured, to smite the wicked and the undead, and to protect the innocent and those who join them in the fight for justice.
<br/>
<br/><strong>BEYOND THE MUNDANE LIFE</strong>
<br/>Almost by definition, the life of a paladin is an adventuring life. Unless a lasting injury has taken him or her away from adventuring for a time, every paladin lives on the front lines of the cosmic struggle against evil. Fighters are rare enough among the ranks of the militias and armies of the world, but even fewer people can c1aim the true calling of a paladin. When they do receive the call, these warriors turn from their former occupations and take up arms to fight evil. Sometimes their oaths lead them into the service of the crown as leaders of elite groups of knights, but even then their loyalty is first to the cause of righteousness, not to crown and country.
<br/>Adventuring paladins take their work seriously. A delve into an ancient ruin or dusty crypt can be a quest driven by a higher purpose than the acquisition of treasure. Evil lurks in dungeons and primeval forests, and even the smallest victory against it can tilt the cosmic balance away from oblivion.', 10, 'Sacred Oath', 'Becoming a paladin involves taking vows that commit the paladin to the cause of righteousness, an active path of fighting wickedness. The final oath, taken when he or she reaches 3rd level, is the culmination of all the paladin''s training. Some characters with this c1ass don''t consider themselves true paladins until they have reached 3rd level and made this oath. For others, the actual swearing of the oath is a formality, an official stamp on what has always been true in the paladin''s heart.', 3, 2, 6, 'paladin.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (8, 'Ranger', 'Far from the bustle of cities and towns, past the hedges that shelter the most distant farms from the terrors of the wild, amid the dense-packed trees of trackless forests and across wide and empty plains, rangers keep their unending watch.
<br/>
<br/><strong>DEADLY HUNTERS</strong>
<br/>Warriors of the wilderness, rangers specialize in hunting the monsters that threaten the edges of civilization - humanoid raiders, rampaging beasts and monstrosities, terrible giants, and deadly dragons. They learn to track their quarry as a predator does, moving stealthily through the wilds and hiding themselves in brush and rubble. Rangers focus their combat training on techniques that are particularly useful against their specific favored foes.
<br/>Thanks to their familiarity with the wilds, rangers acquire the ability to cast spells that harness nature''s power, much as a druid does. Their spells, like their combat abilities, emphasize speed, stealth, and the hunt. A ranger''s talents and abilities are honed with deadly focus on the grim task of protecting the borderlands.
<br/>
<br/><strong>INDEPENDENT ADVENTURERS</strong>
<br/>Though a ranger might make a living as a hunter, a guide, or a tracker, a ranger''s true calling is to defend the outskirts of civilization from the ravages of monsters and humanoid hordes that press in from the wild. In some places, rangers gather in secretive orders or join forces with druidic circles. Many rangers, though, are independent almost to a fault, knowing that, when a dragon or a band of orcs attacks, a ranger might be the first-and possibly the last-line of defense.
<br/>This fierce independence makes rangers well suited to adventuring, since they are accustomed to life far from the comforts of a dry bed and a hot bath. Faced with city-bred adventurers who grouse and whine about the hardships of the wild, rangers respond with some mixture of amusement, frustration, and compassion. But they quickly learn that other adventurers who can carry their own weight in a fight against civilization''s foes are worth any extra burden. Coddled city folk might not know how to feed themselves or find fresh water in the wild, but they make up for it in other ways.', 10, 'Archetype', 'The ideal of the ranger has two classic expressions: the Hunter and the Beast Master.', 3, 3, 5, 'ranger.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (9, 'Rogue', 'Rogues rely on skill, stealth, and their foes'' vulnerabilities to get the upper hand in any situation. They have a knack for finding the solution to just about any problem, demonstrating a resourcefulness and versatility that is the cornerstone of any successful adventuring party.
<br/>
<br/><strong>SKILL AND PRECISION</strong>
<br/>Rogues devote as much effort to mastering the use of a variety of skills as they do to perfecting their combat abilities, giving them a broad expertise that few other characters can match. Many rogues focus on stealth and deception, while others refine the skills that help them in a dungeon environment, such as climbing, finding and disarming traps, and opening locks.
<br/>When it comes to combat, rogues prioritize cunning over brute strength. A rogue would rather make one precise strike, placing it exactly where the attack will hurt the target most, than wear an opponent down with a barrage of attacks. Rogues have an almost supernatural knack for avoiding danger, and a few learn magical tricks to supplement their other abilities.
<br/>
<br/><strong>A SHADY LIVING</strong>
<br/>Every town and city has its share of rogues. Most of them live up to the worst stereotypes of the class, making a living as burglars, assassins, cutpurses, and con artists. Often, these scoundrels are organized into thieves'' guilds or crime families. Plenty of rogues operate independently, but even they sometimes recruit apprentices to help them in their scams and heists. A few rogues make an honest living as locksmiths, investigators, or exterminators, which can be a dangerous job in a world where dire rats-and wererats haunt the sewers.
<br/>As adventurers, rogues fall on both sides of the law. Some are hardened criminals who decide to seek their fortune in treasure hoards, while others take up a life of adventure to escape from the law. Some have learned and perfected their skills with the explicit purpose of infiltrating ancient ruins and hidden crypts in search of treasure.', 8, 'Archetype', 'Rogues have many features in common, including their emphasis on perfecting their skills, their precise and deadly approach to combat, and their increasingly quick reflexes. But different rogues steer those talents in varying directions, embodied by the rogue archetypes. Your choice of archetype is a reflection of your focus not necessarily an indication of your chosen profession, but a description of your preferred techniques.', 3, 4, 4, 'rogue.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (10, 'Sorceror', 'Sorcerers carry a magical birthright conferred upon them by an exotic bloodline, some otherworldly influence. or exposure to unknown cosmic forces. One can''t study sorcery as one learns a language, any more than one can learn to live a legendary life. No one chooses sorcery; the power chooses the sorcerer.
<br/>
<br/><strong>RAW MAGIC</strong>
<br/>Magic is a part of every sorcerer, suffusing body, mind, and spirit with a latent power that waits to be tapped. Some sorcerers wield magic that springs from an ancient bloodline infused with the magic of dragons. Others carry a raw, uncontrolled magic within them, a chaotic storm that manifests in unexpected ways.
<br/>The appearance of sorcerous powers is wildly unpredictable. Some draconic bloodlines produce exactly one sorcerer in every generation, but in other lines of descent every individual is a sorcerer. Most of the time, the talents of sorcery appear as apparent flukes. Some sorcerers can''t name the origin of their power, while others trace it to strange events in their own lives. The touch of a demon, the blessing of a dryad at a baby''s birth, or a taste of the water from a mysterious spring might spark the gift of sorcery. So too might the gift of a deity of magic, exposure to the elemental forces of the Inner Planes or the maddening chaos of Limbo, or a glimpse into the inner workings of reality.
<br/>Sorcerers have no use for the spellbooks and ancient tomes of magic lore that wizards rely on, nor do they rely on a patron to grant their spells as warlocks do. By learning to harness and channel their own inborn magic, they can discover new and staggering ways to unleash that power.
<br/>
<br/><strong>UNEXPLAINED POWERS</strong>
<br/>Sorcerers are rare in the world, and it''s unusual to find a sorcerer who is not involved in the adventuring life in some way. People with magical power seething in their veins soon discover that the power doesn''t like to stay quiet. A sorcerer''s magic wants to be wielded, and it has a tendency to spill out in unpredictable ways if it isn''t called on.
<br/>Sorcerers often have obscure or quixotic motivations driving them to adventure. Some seek a greater understanding of the magical force that infuses them, or the answer to the mystery of its origin. Others hope to find a way to get rid of it, or to unleash its full potential. Whatever their goals, sorcerers are every bit as useful to an adventuring party as wizards, making up for a comparative lack of breadth in their magical knowledge with enormous flexibility in using the spells they know.', 6, 'Sorcerous Origin', 'Different sorcerers c1aim different origins for their innate magic. Although many variations exist, most of these origins fall into two categories: a draconic bloodline and wild magic.', 1, 2, 6, 'sorceror.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (11, 'Warlock', 'Warlocks are seekers of the knowledge that lies hidden in the fabric of the multiverse. Through pacts made with mysterious beings of supernatural power, warlocks unlock magical effects both subtle and spectacular. Drawing on the ancient knowledge of beings such as fey nobles, demons, devils, hags, and alien entities of the Far Realm, warlocks piece together arcane secrets to bolster their own power.
<br/>
<br/><strong>SWORN AND BEHOLDEN</strong>
<br/>A warlock is defined by a pact with an otherworldly being. Sometimes the relationship between warlock and patron is like that of a c1erie and a deity, though the beings that serve as patrons for warlocks are not gods. A warlock might lead a cult dedicated to a demon prince, an archdevil, or an utterly alien entity-beings not typically served by c1erics. More often, though, the arrangement is similar to that between a master and an apprentice. The warlock learns and grows in power, at the cost of occasional services performed on the patron''s behalf.
<br/>The magic bestowed on a warlock ranges from minor but lasting alterations to the warlock''s being (such as the ability to see in darkness or to read any language) to access to powerful spells. Unlike bookish wizards, warlocks supplement their magic with some facility at hand-to-hand combat. They are comfortable in light armor and know how to use simple weapons.
<br/>
<br/><strong>DELVERS INTO SECRETS</strong>
<br/>Warlocks are driven by an insatiable need for knowledge and power, which compels them into their pacts and shapes their lives. This thirst drives warlocks into their pacts and shapes their later careers as well.
<br/>Stories of warlocks binding themselves to fiends are widely known. But many warlocks serve patrons that are not fiendish. Sometimes a traveler in the wilds comes to a strangely beautiful tower, meets its fey lord or lady, and stumbles into a pact without being fully aware of it. And sometimes, while poring over tomes of forbidden lore, a brilliant but crazed student''s mind is opened to realities beyond the material world and to the alien beings that dwell in the outer void.
<br/>Once a pact is made, a warlock''s thirst for knowledge and power can''t be slaked with mere study and research. No one makes a pact with such a mighty patron if he or she doesn''t intend to use the power thus gained. Rather, the vast majority of warlocks spend their days in active pursuit of their goals. which typically means some kind of adventuring. Furthermore, the demands of their patrons drive warlocks toward adventure.', 8, 'Otherworldly Patron', 'The beings that serve as patrons for warlocks are mighty inhabitants of other planes of existence - not gods, but almost godlike in their power. Various patrons give their warlocks access to different powers and invocations, and expect significant favors in return.
<br/>Some patrons collect warlocks, doling out mystic knowledge relatively freely or boasting of their ability to bind mortals to their will. Other patrons bestow their power only grudgingly, and might make a pact with only one warlock. Warlocks who serve the same patron might view each other as allies, siblings, or rivals.', 1, 2, 6, 'warlock.png')

INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId],[ImagePath]) VALUES (12, 'Wizard', 'Wizards are supreme magic-users, defined and united as a class by the spells they cast. Drawing on the subtle weave of magic that permeates the cosmos, wizards cast spel1s of explosive fire, arcing lightning, subtle deception, and brute-force mind control. Their magic conjures monsters from other planes of existence, glimpses the future, or turns slain foes into zombies. Their mightiest spel1s change one substance into another, cal1 meteors down from the sky, or open portals to other worlds.
<br/>
<br/><strong>SCHOLARS OF THE ARCANE</strong>
<br/>Wild and enigmatic, varied in form and function, the power of magic draws students who seek to master its mysteries. Some aspire to become like the gods, shaping reality itself. Though the casting of a typical spel1 requires merely the utterance of a few strange words, fleeting gestures, and sometimes a pinch or clump of exotic materials, these surface components barely hint at the expertise attained after years of apprenticeship and countless hours of study.
<br/>Wizards live and die by their spel1s. Everything else is secondary. They learn new spel1s as they experiment and grow in experience. They can also learn them from other wizards, from ancient tomes or inscriptions, and from ancient creatures (such as the fey) that are steeped in magic.
<br/>
<br/><strong>THE LURE OF KNOWLEDGE</strong>
<br/>Wizards'' lives are seldom mundane, The closest a wizard is likely to come to an ordinary life is working as a sage or lecturer in a library or university, teaching others the secrets of the multiverse. Other wizards sell their services as diviners, serve in military forces, or pursue lives of crime or domination.
<br/>But the lure of knowledge and power calls even the most unadventurous wizards out of the safety of their libraries and laboratories and into crumbling ruins and lost cities. Most wizards believe that their counterparts in ancient civilizations knew secrets of magic that have been lost to the ages, and discovering those secrets could unlock the path to a power greater than any magic available in the present age.', 6, 'Arcane Tradition', 'The study of Wizardry is ancient, stretching back to the earliest mortal discoveries of magic. It is firmly established in fantasy gaming worlds, with various traditions dedicated to its complex study.
<br/>The most Common arcane traditions in the multiverse revolve around The Schools of Magic. Wizards through the ages have cataloged thousands of Spells, grouping them into eight categories called schools. In some places, these traditions are literally schools. In other institutions, the schools are more like academic departments, with rival faculties competing for students and funding. Even wizards who train apprentices in the solitude of their own towers use the division of magic into schools as a learning device, since the Spells of each school require mastery of different Techniques.', 2, 2, 4, 'wizard.png')

GO