CREATE TABLE [dbo].[ClassSkill](
	[Id] [int] NOT NULL,
	[ClassId] [int] NOT NULL,
	[SkillId] [int] NOT NULL,
 CONSTRAINT [PK_ClassSkill] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ClassSkill]  WITH CHECK ADD  CONSTRAINT [FK_ClassSkill_Class] FOREIGN KEY([ClassId])
REFERENCES [dbo].[Class] ([Id])
GO

ALTER TABLE [dbo].[ClassSkill] CHECK CONSTRAINT [FK_ClassSkill_Class]
GO

ALTER TABLE [dbo].[ClassSkill]  WITH CHECK ADD  CONSTRAINT [FK_ClassSkill_Skill] FOREIGN KEY([SkillId])
REFERENCES [dbo].[Skill] ([Id])
GO

ALTER TABLE [dbo].[ClassSkill] CHECK CONSTRAINT [FK_ClassSkill_Skill]
GO