CREATE TABLE [dbo].[Source](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](150) NOT NULL,
	[Code] [nvarchar](10) NOT NULL UNIQUE,
 CONSTRAINT [PK_Source] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
