INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (1, 'Barbarian', '', 12, 'Primal Path', '', 3, 2, 5)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (2, 'Bard', '', 8, 'Bard College', '', 3, 3, 6)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (3, 'Cleric', '', 8, 'Divine Domain', '', 1, 2, 5)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (4, 'Druid', '', 8, 'Druid Circle', '', 2, 2, 5)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (5, 'Fighter', '', 10, 'Martial Archetype', '', 3, 2, 4)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (6, 'Monk', '', 8, 'Monsatic Traditions', '', 3, 2, 5)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (7, 'Paladin', '', 10, 'Sacred Oath', '', 3, 2, 6)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (8, 'Ranger', '', 10, 'Archetype', '', 3, 3, 5)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (9, 'Rogue', '', 8, 'Archetype', '', 3, 4, 4)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (10, 'Sorceror', '', 6, 'Sorcerous Origin', '', 1, 2, 6)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (11, 'Warlock', '', 8, 'Otherworldly Patron', '', 1, 2, 6)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeTypeName],[ArchetypeTypeDescription],[ArchetypeStartingLevel],[NumberOfStartingSkills],[SpellcastingAbilityId]) VALUES (12, 'Wizard', '', 6, 'Arcane Tradition', 'The study of Wizardry is ancient, stretching back to the earliest mortal discoveries of magic. It is firmly established in fantasy gaming worlds, with various traditions dedicated to its complex study.

The most Common arcane traditions in the multiverse revolve around The Schools of Magic. Wizards through the ages have cataloged thousands of Spells, grouping them into eight categories called schools. In some places, these traditions are literally schools. In other institutions, the schools are more like academic departments, with rival faculties competing for students and funding. Even wizards who train apprentices in the solitude of their own towers use the division of magic into schools as a learning device, since the Spells of each school require mastery of different Techniques.', 2, 2, 4)
GO