INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (1, 'Acrobatics', 2)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (2, 'Animal Handling', 5)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (3, 'Arcana', 4)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (4, 'Athletics', 1)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (5, 'Deception', 6)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (6, 'History', 4)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (7, 'Insight', 5)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (8, 'Intimidation', 6)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (9, 'Investigation', 4)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (10, 'Medicine', 5)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (11, 'Nature', 4)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (12, 'Perception', 5)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (13, 'Performance', 6)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (14, 'Persuasion', 6)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (15, 'Religion', 4)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (16, 'Sleight of Hand', 2)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (17, 'Stealth', 2)
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId]) VALUES (18, 'Survival', 5)
GO