INSERT INTO [dbo].[Background] ([Id],[Name],[Description],[AdditionalLanguages]) VALUES (1, 'Acolyte', '', 2)
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (2, 'Charlatan', '')
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (3, 'Criminal', '')
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (4, 'Entertainer', '')
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (5, 'Folk Hero', '')
INSERT INTO [dbo].[Background] ([Id],[Name],[Description],[AdditionalLanguages]) VALUES (6, 'Guild Artisan', '', 1)
INSERT INTO [dbo].[Background] ([Id],[Name],[Description],[AdditionalLanguages]) VALUES (7, 'Hermit', '', 1)
INSERT INTO [dbo].[Background] ([Id],[Name],[Description],[AdditionalLanguages]) VALUES (8, 'Noble', '', 1)
INSERT INTO [dbo].[Background] ([Id],[Name],[Description],[AdditionalLanguages]) VALUES (9, 'Outlander', '', 1)
INSERT INTO [dbo].[Background] ([Id],[Name],[Description],[AdditionalLanguages]) VALUES (10, 'Sage', '', 2)
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (11, 'Sailor', '')
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (12, 'Soldier', '')
INSERT INTO [dbo].[Background] ([Id],[Name],[Description]) VALUES (13, 'Urchin', '')
GO