INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 1,  'Path of the Berserker', 'Berserker', '', 1)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 2,  'Path of the Totem Warrior', 'Totem Warrior', '', 1)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 3,  'College of Lore', 'Lore Bard', '', 2)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 4,  'College of Valor', 'Valor Bard', '', 2)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 5,  'Knowledge Domain', 'Knowledge Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 6,  'Life Domain', 'Life Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 7,  'Light Domain', 'Light Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 8,  'Nature Domain', 'Nature Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 9,  'Tempest Domain', 'Tempest Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 10, 'Trickery Domain', 'Trickery Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 11, 'War Domain', 'War Cleric', '', 3)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 12, 'Circle of the Land', 'Land Druid', '', 4)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 13, 'Circle of the Moon', 'Moon Druid', '', 4)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 14, 'Champion', 'Champion', '', 5)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 15, 'Battle Master', 'Batlle Master', '', 5)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 16, 'Eldritch Knight', 'Eldritch Knight', '', 5)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 17, 'Way of the Open Hand', 'Open Hand Monk', '', 6)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 18, 'Way of Shadow', 'Shadow Monk', '', 6)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 19, 'Way of the Four Elements', 'Four Elements Monk', '', 6)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 20, 'Oath of Devotion', 'Devotion Paladin', '', 7)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 21, 'Oath of the Ancients', 'Ancients Paladin', '', 7)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 22, 'Oath of Vengeance', 'Vengeance Paladin', '', 7)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 23, 'Hunter', 'Hunter', '', 8)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 24, 'Beast Master', 'Beast Master', '', 8)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 25, 'Theif', 'Theif', '', 9)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 26, 'Assassin', 'Assassin', '', 9)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 27, 'Arcane Trickster', 'Arcane Trickster', '', 9)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 28, 'Dragonic Bloodline', 'Draconic Sorceror', '', 10)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 29, 'Wild Magic', 'Wild Magic Sorceror', '', 10)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 30, 'The Archfey', 'Archfey Warlock', '', 11)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 31, 'The Fiend', 'Fiend Warlock', '', 11)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 32, 'The Great Old One', 'Great Old One Warlock', '', 11)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 33, 'School of Abjuration', 'Abjurer', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 34, 'School of Conjuration', 'Conjurer', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 35, 'School of Divination', 'Diviner', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 36, 'School of Enchantment', 'Enchanter', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 37, 'School of Evocation', 'Evoker', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 38, 'School of Illusion', 'Illusionist', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 39, 'School of Necromancy', 'Necromancer', '', 12)
INSERT INTO [dbo].[Archetype] ([Id],[Name],[ShortName],[Description],[ClassId]) VALUES ( 40, 'School of Transmutation', 'Transmuter', '', 12)
GO