INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (1, 'Barbarian', '', 12, 'Primal Path', '', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (2, 'Bard', '', 8, 'Bard College', '', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (3, 'Cleric', '', 8, 'Divine Domain', '', 1)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (4, 'Druid', '', 8, 'Druid Circle', '', 2)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (5, 'Fighter', '', 10, 'Martial Archetype', '', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (6, 'Monk', '', 8, '', 'Monsatic Traditions', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (7, 'Paladin', '', 10, 'Sacred Oath', '', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (8, 'Ranger', '', 10, 'Archetype', '', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (9, 'Rogue', '', 8, 'Archetype', '', 3)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (10, 'Sorceror', '', 6, 'Sorcerous Origin', '', 1)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (11, 'Warlock', '', 8, 'Otherworldly Patron', '', 1)
INSERT INTO [dbo].[Class] ([Id],[Name],[Description],[HitDie],[ArchetypeName],[ArchetypeDescription],[ArchetypeLevel]) VALUES (12, 'Wizard', '', 6, 'Arcane Tradition', '', 2)
GO