INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 1, 'Hill Dwarf', '', 1)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 2, 'Mountain Dwarf', '', 1)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 3, 'High Elf', '', 2)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 4, 'Wood Elf', '', 2)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 5, 'Drow', '', 2)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 6, 'Lightfoot', '', 3)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 7, 'Stout', '', 3)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 8, 'Black Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 9, 'Blue Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 10, 'Brass Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 11, 'Bronze Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 12, 'Copper Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 13, 'Gold Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 14, 'Green Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 15, 'Red Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 16, 'Silver Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 17, 'White Dragonborn', '', 5)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 18, 'Forest Gnome', '', 6)
INSERT INTO [dbo].[SubRace] ([Id],[Name],[Description],[RaceId]) VALUES ( 19, 'Rock Gnome', '', 6)
GO