INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (1, 'Acrobatics', 2, 'Dives, rolls, somersaults and flips.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (2, 'Animal Handling', 5, 'Calm down a domesticated animal, keep a mount from getting spooked, or intuit an animal''s intentions.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (3, 'Arcana', 4, 'Recall lore about spells, magic items and magical traditions.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (4, 'Athletics', 1, 'Climbing, jumping and swimming.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (5, 'Deception', 6, 'Convincingly hide the truth, either verbally or through your actions.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (6, 'History', 4, 'Recall lore about historical events, legendary people and ancient kingdoms.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (7, 'Insight', 5, 'Determine the true intentions of a creature from body language, speech habits, and changes in mannerisms.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (8, 'Intimidation', 6, 'Influence someone through overt threats, hostile actions, and physical violence.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (9, 'Investigation', 4, 'Look around for clues and make deductions based on those clues.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (10, 'Medicine', 5, 'Stabilize a dying companion or diagnose an illness.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (11, 'Nature', 4, 'Recall lore about terrain, natural cycles, plants and animals.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (12, 'Perception', 5, 'Spot, hear, or otherwise detect the presence of something.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (13, 'Performance', 6, 'Delight an audience with music, dance, acting and storytelling')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (14, 'Persuasion', 6, 'Influence someone or a group of people with tact, social graces and good nature.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (15, 'Religion', 4, 'Recall lore about deities, religious hierarchies, rites and prayers.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (16, 'Sleight of Hand', 2, 'Pickpocketing, concealing objects and legerdemain.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (17, 'Stealth', 2, 'Conceal yourself from enemies, slink past guards and slip away without being noticed.')
INSERT INTO [dbo].[Skill] ([Id], [Name], [AbilityId], [Actions]) VALUES (18, 'Survival', 5, 'Follow tracks, hunt wild game and guide your group through natural hazards.')
GO